routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('admin.health.tau');
// });
Route::get('/tes','DashboardController@tes');

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');
Route::group(['middleware' => ['admin'], 'prefix' => 'admin/surat'], function () {
    Route::get('surat-rujukan-kesehatan-anak-sekolah', 'letterController@indexSRKAS')->name('letter.index.srkas');
    Route::post('surat-rujukan-kesehatan-anak-sekolah', 'letterController@printSRKAS')->name('letter.print.srkas');
    Route::get('surat-rujukan-balik', 'letterController@indexRujukBlk')->name('letter.index.rujukblk');
    Route::post('surat-rujukan-balik', 'letterController@printRujukBlk')->name('letter.print.rujukblk');
    Route::get('surat-rujukan-UKS', 'letterController@indexRujukUKS')->name('letter.index.rujukuks');
    Route::post('surat-rujukan-UKS', 'letterController@printRujukUKS')->name('letter.print.rujukuks');
    Route::get('kartu-kontrol','DashboardController@indexkk')->name('karkon.index');
    Route::post('kartu-kontrol','DashboardController@cetak')->name('karkon.cetak');
});

Route::group(['middleware'=>'admin', 'prefix' => 'admin'], function () {
    Route::get('/','DashboardController@index')->name('admin.home');
    Route::resource('user', 'UserController');
    Route::resource('siswa', 'StudentController');
    Route::resource('kesehatan', 'HealthController');
    Route::resource('imunisasi', 'ImmunizationHistoryController');
    Route::resource('status-gizi', 'MeasurementController');
    Route::resource('rekam-medik', 'MedicalRecordController');
    Route::resource('kelas', 'ClassroomController');

    Route::get('siswa-export','StudentController@export')->name('siswa.export');
    Route::post('siswa-import','StudentController@import')->name('siswa.import');

    Route::get('kesehatan/student/{id}', 'HealthController@indexHealth')->name('student.find.health');
    Route::get('kesehatan/create/{id}', 'HealthController@create')->name('kesehatan2.create');

    Route::get('imunisasi/student/{id}', 'ImmunizationHistoryController@indexImmune')->name('student.find.immune');
    Route::get('imunisasi/create/{id}', 'ImmunizationHistoryController@create')->name('imunisasi2.create');

    Route::get('rekam-medik/student/{id}', 'MedicalRecordController@indexMedRec')->name('student.find.record');
    Route::get('rekam-medik/create/{id}', 'MedicalRecordController@create')->name('rekam-medik2.create');

    Route::post('users/update', 'HomeController@tested');
});


// for testing
if (app()->environment(['local', 'staging'])) {
    Route::get('tes',function (){
        return view('welcome');
    });
}

app/Immunization.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Immunization extends Model
{
    protected $fillable = [
        'name',
        'codename',
        'description'
    ];

    public function Immunization_History()
    {
        return $this->belongsToMany('App\ImmunizationHistory');
    }
}

app/Http/Controllers/ImmunizationController.php
<?php

namespace App\Http\Controllers;

use App\Immunization;
use Illuminate\Http\Request;

class ImmunizationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $immunizations = Immunization::all();
        return view('admin.immunization.index',compact('immunizations'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.immunization.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Immunization::create($request->all());
        return redirect()->route('imunisasi.index')->with('success','Berhasil menambah data');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Immunization  $immunization
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
       $immunization = Immunization::findOrFail($id);
       return view('admin.immunization.show',compact('immunization'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Immunization  $immunization
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $immunization = Immunization::findOrFail($id);
        return view('admin.immunization.show',compact('immunization'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Immunization  $immunization
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Immunization::update($request->all());
        return redirect()->route('imunisasi.index')->with('success','Berhasil merubah data');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Immunization  $immunization
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Immunization::findOrFail($id);
        return redirect()->route('imunisasi.index')->with('success','Berhasil menghapus data');
    }
}

resources/views/admin/immunization/form.blade.php
@extends('layouts.layout')

@section('content')
<!-- Breadcrumb-->
<div class="breadcrumb-holder">
    <div class="container-fluid">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="index.html">Home</a></li>
            <li class="breadcrumb-item active">Anak </li>
        </ul>
    </div>
</div>
<section>
    <div class="container-fluid">
        <!-- Page Header-->
        <header>
            <h1 class="h3 display">Anak </h1>
        </header>
        <div class="card">
            <div class="card-body">
                <div class="media align-items-center"><span
                        style="background-image: url({{asset('uploads/avatars/'.$student->avatar)}})"
                        class="avatar avatar-xl mr-3"></span>
                    <div class="media-body overflow-hidden">
                        <h5 class="card-text mb-0">{{$student->name}}</h5>
                        <p class="card-text text-uppercase">Kelas {{$student->classroom ?? ''}}</p>
                        <p class="card-text">

                            NIK: {{$student->nis}}<br>bla
                        </p>
                    </div>
                </div><a href="#" class="tile-link"></a>
            </div>
        </div>
    @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            <li>Proses Gagal!!!</li>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                @isset ($record)
                <div class="card-header d-flex align-items-center">
                    <h4>Ubah Imunisasi</h4>
                </div>
                <div class="card-body">
                    <form enctype="multipart/form-data" action="{{route('imunisasi.update',$record->id)}}"
                        method="POST">
                        @method('PUT')
                        @else
                        <div class="card-header d-flex align-items-center">
                            <h4>Tambah imunisasi</h4>
                        </div>
                        <div class="card-body">
                            <form enctype="multipart/form-data" action="{{route('imunisasi.store',$student->nis)}}"
                                method="POST">
                                @endisset
                                @csrf
                                <div class="form-group">
                                    <label>Tanggal Pelaksanaan</label>
                                    <input type="date" name="date" class="form-control" value="{{old('date', $record->date ?? ' ')}}" required>
                                </div>
                                <div class="row">
                                    <div class="form-group col-lg-6">
                                        <label>Usia (total bulan/tahun dan bulan)</label>
                                        @isset($record)
                                        <input type="text" name="totalMonth" class="totalMonth form-control"
                                            value="{{12 * $record->age_year + $record->age_month}} bulan / {{$record->age_year}} Tahun {{$record->age_month}} Bulan" disabled>
                                        @else
                                        <input type="text" name="totalMonth" class="totalMonth form-control"
                                            value="{{12 * $ageYear + $ageMonth}} bulan / {{$ageYear}} Tahun {{$ageMonth}} Bulan" disabled>
                                        @endisset

                                    </div>
                                    @isset($record)
                                    <input type="hidden" name="age_year" value="{{$record->age_year}}">
                                    <input type="hidden" name="age_month" value="{{$record->age_month}}">
                                    @else
                                    <input type="hidden" name="age_year" value="{{$ageYear}}">
                                    <input type="hidden" name="age_month" value="{{$ageMonth}}">
                                    @endisset
                                </div>
                                <div class="form-group row">
                                    <label class="col-sm-3 form-control-label">Imunisasi <br><small
                                            class="text-primary">Silahkan Dicentang</small></label>
                                    <div class="col-sm-9">
                                        @isset($record)
                                @foreach ($record->immunization as $item)
                                <div class="i-checks">
                                    <input id="checkboxCustom{{$item->id}}" type="checkbox" name="{{$item->name}}" value="1"
                                        class="form-control-custom" @if ($item->pivot->status) checked="" @endif>
                                    <label for="checkboxCustom{{$item->id}}">{{$item->name}}</label>
                                </div>
                                @endforeach
                                @else
                                @foreach ($immunizations as $item)
                                <div class="i-checks">
                                    <input id="checkboxCustom{{$item->id}}1" type="checkbox" name="{{$item->name}}" value="1"
                                        class="form-control-custom">
                                    <label for="checkboxCustom{{$item->id}}1">{{$item->name}}</label>
                                </div>
                                @endforeach
                                @endisset
                                    </div>
                                </div>
                                <input type="hidden" name="student_nis" value="{{$student->nis}}">
                                <br>
                                <div class="form-group">
                                    <input type="submit" value="Simpan" class="btn btn-primary">
                                    <a href="{{URL::previous()}}" class="btn btn-danger">Batal</a>
                                </div>
                            </form>
                        </div>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

resources/views/admin/immunization/index3.blade.php
@extends('layouts.layout')

@section('content')
<!-- Breadcrumb-->
<div class="breadcrumb-holder">
    <div class="container-fluid">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="index.html">Home</a></li>
            <li class="breadcrumb-item active">imunisasi </li>
        </ul>
    </div>
</div>
<section>
    <div class="container-fluid">
        <!-- Page Header-->
        <header>
            <h1 class="h3 display">List Data imunisasi </h1>
        </header>
        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        @endif
        @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
        @endif
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header">
                        <h4 style="float:left">
                            {{$student->name}}
                        </h4>
                        <div style="float:right">
                            <a href="{{route('imunisasi2.create',$student->nis)}}" class="btn btn-primary btn-sm">Tambah</a>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Tanggal Pelaksanaan</th>
                                        <th>Usia</th>
                                        <th>Aksi</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php $x=1;?>
                                    @foreach ($records as $item)
                                    <tr>
                                        <th scope="row">{{$x++}}</th>
                                        <td>{{date('d-m-Y',strtotime($item->date))}}</td>
                                        <td>{{$item->age_year}} Tahun {{$item->age_month}} Bulan</td>
                                        <td>
                                            <form action="{{ route('imunisasi.destroy',$item->id) }}" method="POST">
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit" onclick="return confirm('Apakah anda yakin?')"
                                                    class="btn btn-danger btn-sm"><i
                                                        class="fa fa-trash"></i></button>

                                                <a href="{{route('imunisasi.edit',$item->id)}}"
                                                    class="btn btn-warning btn-sm"><i class="fa fa-edit"></i></a>
                                                <a href="{{route('imunisasi.show',$item->id)}}"
                                                    class="btn btn-primary btn-sm"><i class="fa fa-eye"></i></a>
                                            </form>
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

resources/views/admin/immunization/index_student.blade.php
@extends('layouts.layout')

@section('content')
<!-- Breadcrumb-->
<div class="breadcrumb-holder">
    <div class="container-fluid">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{url('/')}}">Home</a></li>
            <li class="breadcrumb-item active">Imunisasi</li>
        </ul>
    </div>
</div>
<section>
    <div class="container-fluid">
        <!-- Page Header-->
        <header>
            <h1 class="h3 display">List Anak </h1>
        </header>
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header">

                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table" id="student-table">
                                <thead>
                                    <tr>
                                        <th class="text-center">Nama</th>
                                        <th class="text-center">NIK</th>
                                        <th class="text-center">Kelas</th>

                                    </tr>
                                </thead>
                                <tbody></tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

@section('custom-script')
<script>
    $(document).ready(function() {
        $('#student-table').DataTable({
            processing: true,
            serverSide: true,
            ajax:"{{ route('imunisasi.index') }}",
            columns:[

            {data: 'name', name: 'name'},
            {data: 'nis', name: 'nis'},
            {data: 'classroom', name: 'classroom'},
            ]
        });
    })
</script>
@endsection