routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('admin.health.tau');
// });
Route::get('/tes','DashboardController@tes');

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');
Route::group(['middleware' => ['admin'], 'prefix' => 'admin/surat'], function () {
    Route::get('surat-rujukan-kesehatan-anak-sekolah', 'letterController@indexSRKAS')->name('letter.index.srkas');
    Route::post('surat-rujukan-kesehatan-anak-sekolah', 'letterController@printSRKAS')->name('letter.print.srkas');
    Route::get('surat-rujukan-balik', 'letterController@indexRujukBlk')->name('letter.index.rujukblk');
    Route::post('surat-rujukan-balik', 'letterController@printRujukBlk')->name('letter.print.rujukblk');
    Route::get('surat-rujukan-UKS', 'letterController@indexRujukUKS')->name('letter.index.rujukuks');
    Route::post('surat-rujukan-UKS', 'letterController@printRujukUKS')->name('letter.print.rujukuks');
    Route::get('kartu-kontrol','DashboardController@indexkk')->name('karkon.index');
    Route::post('kartu-kontrol','DashboardController@cetak')->name('karkon.cetak');
});

Route::group(['middleware'=>'admin', 'prefix' => 'admin'], function () {
    Route::get('/','DashboardController@index')->name('admin.home');
    Route::resource('user', 'UserController');
    Route::resource('siswa', 'StudentController');
    Route::resource('kesehatan', 'HealthController');
    Route::resource('imunisasi', 'ImmunizationHistoryController');
    Route::resource('status-gizi', 'MeasurementController');
    Route::resource('rekam-medik', 'MedicalRecordController');
    Route::resource('kelas', 'ClassroomController');

    Route::get('siswa-export','StudentController@export')->name('siswa.export');
    Route::post('siswa-import','StudentController@import')->name('siswa.import');

    Route::get('kesehatan/student/{id}', 'HealthController@indexHealth')->name('student.find.health');
    Route::get('kesehatan/create/{id}', 'HealthController@create')->name('kesehatan2.create');

    Route::get('imunisasi/student/{id}', 'ImmunizationHistoryController@indexImmune')->name('student.find.immune');
    Route::get('imunisasi/create/{id}', 'ImmunizationHistoryController@create')->name('imunisasi2.create');

    Route::get('rekam-medik/student/{id}', 'MedicalRecordController@indexMedRec')->name('student.find.record');
    Route::get('rekam-medik/create/{id}', 'MedicalRecordController@create')->name('rekam-medik2.create');

    Route::post('users/update', 'HomeController@tested');
});


// for testing
if (app()->environment(['local', 'staging'])) {
    Route::get('tes',function (){
        return view('welcome');
    });
}

resources/views/admin/home.blade.php
@extends('layouts.layout')

@section('content')
<section class="dashboard-counts section-padding">
    <div class="container-fluid">
        <div class="row">
            <!-- Count item widget-->
            <div class="col-xl-2 col-md-4 col-6">
                <div class="wrapper count-title d-flex">
                    <div class="icon"><i class="icon-user"></i></div>
                    <div class="name"><strong class="text-uppercase">Total Anak</strong>
                        <div class="count-number">{{$total_student}}</div>
                    </div>
                </div>
            </div>
            <!-- Count item widget-->
            <div class="col-xl-2 col-md-4 col-6">
                <div class="wrapper count-title d-flex">
                    <div class="icon"><i class="icon-user"></i></div>
                    <div class="name"><strong class="text-uppercase">Anak Laki-laki</strong>
                        <div class="count-number">{{$total_boy}}</div>
                    </div>
                </div>
            </div>
            <!-- Count item widget-->
            <div class="col-xl-2 col-md-4 col-6">
                <div class="wrapper count-title d-flex">
                    <div class="icon"><i class="icon-user"></i></div>
                    <div class="name"><strong class="text-uppercase">Anak Perempuan</strong>
                        <div class="count-number">{{$total_girl}}</div>
                    </div>
                </div>
            </div>
            <!-- Count item widget-->
            {{-- <div class="col-xl-2 col-md-4 col-6">
          <div class="wrapper count-title d-flex">
            <div class="icon"><i class="icon-list-1"></i></div>
            <div class="name"><strong class="text-uppercase">Tidak Diketahui</strong><span>Tidak Diketahui</span>
              <div class="count-number">0</div>
            </div>
          </div>
        </div> --}}
        </div>
    </div>
</section>
<!-- Header Section-->
<section class="dashboard-header section-padding">
    <div class="container-fluid">
        <div class="row d-flex align-items-md-stretch">

            <!-- Line Chart -->
            <div class="col-lg-6 col-md-12 flex-lg-last flex-md-first align-self-baseline">
                <div class="card sales-report">
                    <h2 class="display h4">Grafik Tinggi Badan Anak</h2>
                    <p>Laki-laki dan Perempuan</p>
                    <div class="line-chart">
                        <canvas id="lineCahrt"></canvas>
                    </div>
                </div>
            </div>
            <!-- Pie Chart-->
            <div class="col-lg-3 col-md-6">
                {{-- <div class="card project-progress">
            <h2 class="display h4">Project Beta progress</h2>
            <p> Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
            <div class="pie-chart">
              <canvas id="pieChart" width="300" height="300"> </canvas>
            </div>
          </div> --}}
            </div>
        </div>
    </div>
</section>
<!-- Statistics Section-->
<section class="statistics">
    <div class="container-fluid">
        <div class="row d-flex">
            <div class="col-lg-4">
                <!-- Income-->
                {{-- <div class="card income text-center">
            <div class="icon"><i class="icon-line-chart"></i></div>
            <div class="number">126,418</div><strong class="text-primary">All Income</strong>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit sed do.</p>
          </div> --}}
            </div>
            <div class="col-lg-4">
                <!-- Monthly Usage-->
                {{-- <div class="card data-usage">
            <h2 class="display h4">Monthly Usage</h2>
            <div class="row d-flex align-items-center">
              <div class="col-sm-6">
                <div id="progress-circle" class="d-flex align-items-center justify-content-center"></div>
              </div>
              <div class="col-sm-6"><strong class="text-primary">80.56 Gb</strong><small>Current Plan</small><span>100 Gb Monthly</span></div>
            </div>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing.</p>
          </div> --}}
            </div>
            <div class="col-lg-4">
                <!-- User Actibity-->
                {{-- <div class="card user-activity">
            <h2 class="display h4">User Activity</h2>
            <div class="number">210</div>
            <h3 class="h4 display">Social Users</h3>
            <div class="progress">
              <div role="progressbar" style="width: 25%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100" class="progress-bar progress-bar bg-primary"></div>
            </div>
            <div class="page-statistics d-flex justify-content-between">
              <div class="page-statistics-left"><span>Pages Visits</span><strong>230</strong></div>
              <div class="page-statistics-right"><span>New Visits</span><strong>73.4%</strong></div>
            </div>
          </div> --}}
            </div>
        </div>
    </div>
</section>
@endsection

@section('script')
<script src="{{asset('template/vendor/chart.js/Chart.min.js')}}"></script>
<script src="{{asset('template/js/charts-home.js')}}"></script>
<script src="{{asset('template/js/home-premium.js')}}"> </script>
@endsection

resources/views/admin/layout.blade.php
@extends('layouts.proyek')
@section('contents')
@yield('content')
<div>
    <p> </p>
</div>
@endsection
@if (Auth::user()->user_type=="admin")
@section('sidebar')
<div class="main-menu">
    <h5 class="sidenav-heading">Menu</h5>
    <ul id="side-main-menu" class="side-menu list-unstyled">
        {{-- <li><a href="{{route('guest.index')}}"> <i class="fa fa-home"></i>Home </a></li>
        <li><a href="{{route('siswa.index')}}"> <i class="fa fa-user-graduate"></i>Data Siswa </a></li>
        <li><a href="{{route('kesehatan.index')}}"> <i class="fa fa-notes-medical"></i>Data Kesehatan </a></li>
        <li><a href="{{route('imunisasi.index')}}"> <i class="fa fa-stethoscope"></i>Data Imunisasi </a></li>
        <li><a href="{{route('rekammedik.index')}}"> <i class="fa fa-book-medical"></i>Data Penjaringan Kesehatan Anak
            </a></li> --}}
        <li><a href="#Dropdown1" aria-expanded="false" data-toggle="collapse"> <i class="fas fa-envelope"></i>Master
            </a>
            <ul id="Dropdown1" class="collapse list-unstyled ">
                <li><a href="{{route('user.index')}}"><i class="far fa-envelope"></i>Pengguna</a></li>
                <li><a href="{{route('siswa.index')}}"><i class="far fa-envelope"></i>Anak</a></li>
                <li><a href="{{route('user.index')}}"><i class="far fa-envelope"></i>Kelas Anak</a></li>
                <li><a href="{{route('user.index')}}"><i class="far fa-envelope"></i>Kategori Pengguna</a></li>
                <li><a href="{{route('user.index')}}"><i class="far fa-envelope"></i>Kondisi Kesehatan</a></li>
                <li><a href="{{route('user.index')}}"><i class="far fa-envelope"></i>Hasil Kesehatan</a></li>
                <li><a href="{{route('user.index')}}"><i class="far fa-envelope"></i>Hasil Pengukuran</a></li>
            </ul>
        </li>
        {{-- <li><a href="#exampledropdownDropdown1" aria-expanded="false" data-toggle="collapse"> <i
                    class="fas fa-envelope"></i>Surat Rujukan </a>
            <ul id="exampledropdownDropdown1" class="collapse list-unstyled ">
                <li><a href="{{route('rujuk.index')}}"><i class="far fa-envelope"></i>Rujukan Kesehatan</a></li>
        <li><a href="{{route('rujukB.index')}}"><i class="far fa-envelope"></i>Rujukan Balik</a></li>
        <li><a href="{{route('rujukUKS.index')}}"><i class="far fa-envelope"></i>Rujukan UKS</a></li>
    </ul>
    </li>
    <li><a href="#exampledropdownDropdown" aria-expanded="false" data-toggle="collapse"> <i class="fa fa-book"></i>Pojok
            Baca </a>
        <ul id="exampledropdownDropdown" class="collapse list-unstyled ">
            <li><a href="{{route('modul.index')}}"><i class="fa fa-book"></i>Buku</a></li>
            <li><a href="{{route('katmodul.index')}}"><i class="fa fa-book"></i>Kategori Buku</a></li>
        </ul>
    </li>
    <li><a href="{{route('karkon.index')}}"> <i class="fas fa-table"></i>Kartu Kontrol </a></li>
    <li><a href="{{route('user.index')}}"> <i class="fa fa-users"></i>Pengguna </a></li> --}}

    {{-- <li> <a href="#"> <i class="icon-mail"></i>Demo
              <div class="badge badge-warning">6 New</div></a>
        </li> --}}
    </ul>
</div>

@endsection
@else
@section('sidebar')
<div class="main-menu">
    <h5 class="sidenav-heading">Main</h5>
    <ul id="side-main-menu" class="side-menu list-unstyled">
        <li><a href="{{route('guest.index')}}"> <i class="fa fa-home"></i>Home </a></li>
        @if (Auth::user())
        @if (Auth::user()->status=="ADMIN"||Auth::user()->status=="GURU"||Auth::user()->status=="UMUM")
        <li><a href="{{route('rekammedik.index')}}"> <i class="fa fa-book-medical"></i>Data Penjaringan Kesehatan Anak
            </a></li>
        @endif
        @endif
        <li><a href="{{route('guest.pojokbaca')}}"> <i class="fa fa-book"></i>Pojok Baca </a></li>
    </ul>
</div>

@endsection
@section('script')

@endsection
@endif