routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('admin.health.tau');
// });
Route::get('/tes','DashboardController@tes');

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');
Route::group(['middleware' => ['admin'], 'prefix' => 'admin/surat'], function () {
    Route::get('surat-rujukan-kesehatan-anak-sekolah', 'letterController@indexSRKAS')->name('letter.index.srkas');
    Route::post('surat-rujukan-kesehatan-anak-sekolah', 'letterController@printSRKAS')->name('letter.print.srkas');
    Route::get('surat-rujukan-balik', 'letterController@indexRujukBlk')->name('letter.index.rujukblk');
    Route::post('surat-rujukan-balik', 'letterController@printRujukBlk')->name('letter.print.rujukblk');
    Route::get('surat-rujukan-UKS', 'letterController@indexRujukUKS')->name('letter.index.rujukuks');
    Route::post('surat-rujukan-UKS', 'letterController@printRujukUKS')->name('letter.print.rujukuks');
    Route::get('kartu-kontrol','DashboardController@indexkk')->name('karkon.index');
    Route::post('kartu-kontrol','DashboardController@cetak')->name('karkon.cetak');
});

Route::group(['middleware'=>'admin', 'prefix' => 'admin'], function () {
    Route::get('/','DashboardController@index')->name('admin.home');
    Route::resource('user', 'UserController');
    Route::resource('siswa', 'StudentController');
    Route::resource('kesehatan', 'HealthController');
    Route::resource('imunisasi', 'ImmunizationHistoryController');
    Route::resource('status-gizi', 'MeasurementController');
    Route::resource('rekam-medik', 'MedicalRecordController');
    Route::resource('kelas', 'ClassroomController');

    Route::get('siswa-export','StudentController@export')->name('siswa.export');
    Route::post('siswa-import','StudentController@import')->name('siswa.import');

    Route::get('kesehatan/student/{id}', 'HealthController@indexHealth')->name('student.find.health');
    Route::get('kesehatan/create/{id}', 'HealthController@create')->name('kesehatan2.create');

    Route::get('imunisasi/student/{id}', 'ImmunizationHistoryController@indexImmune')->name('student.find.immune');
    Route::get('imunisasi/create/{id}', 'ImmunizationHistoryController@create')->name('imunisasi2.create');

    Route::get('rekam-medik/student/{id}', 'MedicalRecordController@indexMedRec')->name('student.find.record');
    Route::get('rekam-medik/create/{id}', 'MedicalRecordController@create')->name('rekam-medik2.create');

    Route::post('users/update', 'HomeController@tested');
});


// for testing
if (app()->environment(['local', 'staging'])) {
    Route::get('tes',function (){
        return view('welcome');
    });
}

app/MedicalRecord.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class MedicalRecord extends Model
{
    protected $fillable = [
        'date',
        'student_nis',
    ];

    public function learningModality()
    {
        return $this->belongsToMany('App\LearningModality','medical_record_lm','medical_record_id','learning_modalities_id')
                    ->withPivot('score')
                    ->withTimestamps();
    }

    public function mentalHealth()
    {
        return $this->belongsToMany('App\MentalHealth','medical_record_mh')
                    ->withPivot('score')
                    ->withTimestamps();
    }

    public function mentalHealth2()
    {
        return $this->belongsToMany('App\MentalHealth2','medical_record_mh2','medical_record_id','mental_healths2_id')
                    ->withPivot('score')
                    ->withTimestamps();
    }

    public function brainDomination()
    {
        return $this->belongsToMany('App\BrainDomination','medical_record_bd')
                    ->withPivot('score')
                    ->withTimestamps();
    }

    public function healthScreening()
    {
        return $this->belongsToMany('App\HealthScreening','medical_record_hs')
                    ->withPivot('choice')
                    ->withPivot('description')
                    ->withTimestamps();
    }

    public function student()
    {
        return $this->belongsTo('App\Student','student_nis');
    }
}

app/Http/Controllers/MedicalRecordController.php
<?php

namespace App\Http\Controllers;

use App\BrainDomination;
use App\HealthScreening;
use App\LearningModality;
use App\MedicalRecord;
use App\MentalHealth;
use App\MentalHealth2;
use App\Student;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class MedicalRecordController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(request()->ajax()){
            $data = Student::all();
            return datatables()->of($data)
                    ->editColumn('name', function($data){
                        $name = '<a href="'.route("student.find.record", $data->nis).'">'.$data->name.'</a>';
                        return $name;
                    })
                    ->rawColumns(['name'])
                    ->make(true);
        }
        return view('admin.medical_record.index_student');
    }

    public function indexMedRec($id)
    {
        $records = MedicalRecord::where('student_nis','=',$id)->get();
        $student = Student::findOrFail($id);
        return view('admin.medical_record.index3',compact('records','student'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($id)
    {
        $student = Student::findOrFail($id);
        $mentalHealths = MentalHealth::all();
        $mentalHealths2 = MentalHealth2::all();
        $learningModalities = LearningModality::all();
        $brainDominations = BrainDomination::all();

        return view('admin.medical_record.form',compact('student','mentalHealths','mentalHealths2','learningModalities','brainDominations'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $student = Student::findOrFail($request->student_nis);
        $medicalRecord = MedicalRecord::create($request->all());
        $a = HealthScreening::all();
        $mh = MentalHealth::all();
        // $mh2 = MentalHealth2::all();
        $lm = LearningModality::all();
        $bd = BrainDomination::all();
        $x = 1;
        foreach ($a as $item) {
            //collect all inserted record IDs
            $a_id_array[$item->id] = [
                'choice' => $request->a[$x],
                'description' => $request->ket_a[$x++]
            ];
        }
        $x = 1;
        foreach ($mh as $item) {
            //collect all inserted record IDs
            $mh_id_array[$item->id] = ['score' => $request->mh[$x++]];
        }
        // $x = 1;
        // foreach ($mh2 as $item) {
        //     //collect all inserted record IDs
        //     $mh2_id_array[$item->id] = ['score' => $request->mh2[$x++]];
        // }
        $x = 1;
        foreach ($lm as $item) {
            //collect all inserted record IDs
            $lm_id_array[$item->id] = ['score' => $request->lm[$x++]];
        }
        $x = 1;
        foreach ($bd as $item) {
            //collect all inserted record IDs
            $bd_id_array[$item->id] = ['score' => $request->bd[$x++]];
        }

        DB::beginTransaction();
        try {
            $medicalRecord->mentalHealth()->attach($mh_id_array);
            // $medicalRecord->mentalHealth2()->attach($mh2_id_array);
            $medicalRecord->learningModality()->attach($lm_id_array);
            $medicalRecord->brainDomination()->attach($bd_id_array);
            $medicalRecord->healthScreening()->attach($a_id_array);
            DB::commit();
        } catch (\Exception $e){
            DB::rollBack();
            return redirect()->route('rekam-medik.create')->withErrors(['message'=>$e->getMessage()]);
        }

        return redirect()->route('student.find.record',$request->student_nis)->with(['success'=>'Berhasil menambah data','data'=>$student]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\MedicalRecord  $medicalRecord
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $show = MedicalRecord::with('mentalHealth')->with('mentalHealth2')->with('brainDomination')->with('learningModality')->with('healthScreening')->findOrFail($id);
        $student = Student::findOrFail($show->student_nis);

        $mentalHealths = MentalHealth::all();
        $mentalHealths2 = MentalHealth2::all();
        $learningModalities = LearningModality::all();
        $brainDominations = BrainDomination::all();

        $choice1 = ['ya','tidak'];
        $choice2 = ['ya','tidak','1 kali','lebih dari 1 kali'];
        $choice3 = ['ya','tidak','tidak tahu'];
        $choice4 = ['selalu','kadang-kadang','tidak pernah'];
        $choice5 = ['ada','kadang-kadang','tidak ada'];

        return view('admin.medical_record.form',compact(
            'show',
            'student',
            'mentalHealths',
            'mentalHealths2',
            'learningModalities',
            'brainDominations',
            'choice1',
            'choice2',
            'choice3',
            'choice4',
            'choice5',
        ));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\MedicalRecord  $medicalRecord
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $record = MedicalRecord::with('mentalHealth')->with('mentalHealth2')->with('brainDomination')->with('learningModality')->with('healthScreening')->findOrFail($id);
        $student = Student::findOrFail($record->student_nis);

        $mentalHealths = MentalHealth::all();
        $mentalHealths2 = MentalHealth2::all();
        $learningModalities = LearningModality::all();
        $brainDominations = BrainDomination::all();

        $choice1 = ['ya','tidak'];
        $choice2 = ['ya','tidak','1 kali','lebih dari 1 kali'];
        $choice3 = ['ya','tidak','tidak tahu'];
        $choice4 = ['selalu','kadang-kadang','tidak pernah'];
        $choice5 = ['ada','kadang-kadang','tidak ada'];


        return view('admin.medical_record.form',compact(
            'record',
            'student',
            'mentalHealths',
            'mentalHealths2',
            'learningModalities',
            'brainDominations',
            'choice1',
            'choice2',
            'choice3',
            'choice4',
            'choice5',
        ));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\MedicalRecord  $medicalRecord
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $student = Student::findOrFail($request->student_nis);
        $medicalRecord = MedicalRecord::findOrFail($id);
        $medicalRecord->update($request->all());
        $a = HealthScreening::all();
        $mh = MentalHealth::all();
        $mh2 = MentalHealth2::all();
        $lm = LearningModality::all();
        $bd = BrainDomination::all();
        $x = 1;
        foreach ($a as $item) {
            //collect all inserted record IDs
            $a_id_array[$item->id] = [
                'choice' => $request->a[$x],
                'description' => $request->ket_a[$x++]
            ];
        }
        $x = 1;
        foreach ($mh as $item) {
            //collect all inserted record IDs
            $mh_id_array[$item->id] = ['score' => $request->mh[$x++]];
        }
        $x = 1;
        foreach ($mh2 as $item) {
            //collect all inserted record IDs
            $mh2_id_array[$item->id] = ['score' => $request->mh2[$x++]];
        }
        $x = 1;
        foreach ($lm as $item) {
            //collect all inserted record IDs
            $lm_id_array[$item->id] = ['score' => $request->lm[$x++]];
        }
        $x = 1;
        foreach ($bd as $item) {
            //collect all inserted record IDs
            $bd_id_array[$item->id] = ['score' => $request->bd[$x++]];
        }

        $medicalRecord->mentalHealth()->syncWithoutDetaching($mh_id_array);
        $medicalRecord->mentalHealth2()->syncWithoutDetaching($mh2_id_array);
        $medicalRecord->learningModality()->syncWithoutDetaching($lm_id_array);
        $medicalRecord->brainDomination()->syncWithoutDetaching($bd_id_array);
        $medicalRecord->healthScreening()->syncWithoutDetaching($a_id_array);
        return redirect()->route('student.find.record',$request->student_nis)->with(['success'=>'Berhasil merubah data','data'=>$student]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\MedicalRecord  $medicalRecord
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        MedicalRecord::findOrFail($id)->delete();
        return redirect()->route('rekam-medik.index')->with('success','Berhasil menghapus data');
    }

    public function searchStudent(Request $request)
    {
        $students = Student::search($request->name)->get();
        $search = $request->name;
        return view('admin.medical_record.index_student',compact('students','search'));
    }
}

resources/views/admin/medical_record/brain_domination.blade.php
<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>Pertanyaan</th>
                <th>Skor</th>
            </tr>
        </thead>
        <tbody>
            <?php $x=1;?>
            @isset($show)
            @foreach ($brainDominations as $item)
            <tr>
                <td>{{$x}}</td>
                <td>{{$item->question}}</td>
                <td>{{$item->type}}</td>
                <td class="brain-domination" id="bd{{$x++}}">{{$show->brainDomination->find($item->id)->pivot->score ?? 0}}</td>
            </tr>
            @endforeach
            @else
                <?php $x=1;?>
                @isset($record)
                @foreach ($brainDominations as $item)
                <tr>
                    <td>{{$x}}</td>
                    <td>{{$item->question}}</td>
                    <td><input type="number" name="bd[{{$x}}]" id="bd{{$x}}" style="width:50px" class="brain-domination"
                        value="{{old('bd['.$x++.']', $record->brainDomination->find($item->id)->pivot->score ?? ' ')}}" min="0" max="1"></td>
                </tr>
                @endforeach
                @else
                @foreach ($brainDominations as $item)
                <tr>
                    <td>{{$x}}</td>
                    <td>{{$item->question}}</td>
                    <td><input class="brain-domination" type="number" name="bd[{{$x}}]" id="bd{{$x++}}" style="width:50px" min="0" max="1" value="0"></td>
                </tr>
                @endforeach
                @endisset
            @endisset
        </tbody>
    </table>
</div>
<br>
<div style="border: 1 solid black">
    <label>Interpretasi:</label>
    <p id="interpretation">Silahkan isi data diatas terlebih dahulu</p>
</div>

resources/views/admin/medical_record/form.blade.php
@extends('layouts.layout')

@section('content')
<!-- Breadcrumb-->
<div class="breadcrumb-holder">
    <div class="container-fluid">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="index.html">Home</a></li>
            <li class="breadcrumb-item active">Rekam Medik </li>
        </ul>
    </div>
</div>
<section>
    <div class="container-fluid">
        <!-- Page Header-->
        <header>
            <h1 class="h3 display">Rekam Medik </h1>
        </header>
        <div class="card">
            <div class="card-body">
                <div class="media align-items-center"><span
                        style="background-image: url({{asset('uploads/avatars/'.$student->avatar)}})"
                        class="avatar avatar-xl mr-3"></span>
                    <div class="media-body overflow-hidden">
                        <h5 class="card-text mb-0">{{$student->name}}</h5>
                        <p class="card-text text-uppercase">Kelas {{$student->classroom ?? ''}}</p>
                        <p class="card-text">NIK: {{$student->nis ?? "belum diatur"}}<br></p>
                    </div>
                </div><a href="#" class="tile-link"></a>
            </div>
        </div>
    @if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            <li>Proses Gagal!!!</li>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif
    <div class="row">
        <div class="col-lg-12">
            @isset($show)
            <div class="card">
                <div class="card-header d-flex align-items-center">
                    <h4>Lihat Rekam Medik</h4>
                </div>
                <div class="card-body">
                    <div class="form-group">
                        <p style="color: black;font-weight: bold;">Tgl Pemeriksaan : {{$show->date}}</p>
                    </div>
                    <ul class="nav nav-tabs">
                        <li class="nav-item">
                            <a class="nav-link active" data-toggle="tab" href="#hs">Penjanringan Kesehatan</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link" data-toggle="tab" href="#mh">Kesehatan Mental</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" data-toggle="tab" href="#lm">Modalitas Belajar</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" data-toggle="tab" href="#bd">Dominasi Otak</a>
                        </li>
                    </ul>
                      <!-- Tab panes -->
                      <div class="tab-content">
                        <div class="tab-pane container active" id="hs">
                            @isset($record)
                            @include('admin.medical_record.health_screening',['record'=>$record])
                            @else
                            @include('admin.medical_record.health_screening')
                            @endisset
                        </div>
                        <div class="tab-pane container fade" id="mh">
                            @include('admin.medical_record.mental_health')
                        </div>
                        <div class="tab-pane container fade" id="lm">
                            @include('admin.medical_record.learning_modality')
                        </div>
                        <div class="tab-pane container fade" id="bd">
                            @include('admin.medical_record.brain_domination')
                        </div>
                      </div>
                </div>
            </div>
            @else
            <div class="card">
                @isset ($record)
                <div class="card-header d-flex align-items-center">
                    <h4>Ubah Rekam Medik</h4>
                </div>
                <div class="card-body">
                    <form enctype="multipart/form-data" action="{{route('rekam-medik.update',$record->id)}}"
                        method="POST">
                        @method('PUT')
                        @else
                        <div class="card-header d-flex align-items-center">
                            <h4>Tambah Rekam Medik</h4>
                        </div>
                        <div class="card-body">
                            <form enctype="multipart/form-data" action="{{route('rekam-medik.store')}}"
                                method="POST">
                                @endisset
                                @csrf
                                <div class="form-group">
                                    <label>Tanggal Pemeriksaan</label>
                                    <input type="date" name="date" class="form-control" value="{{old('date', $record->date ?? ' ')}}" required>
                                </div>
                                <ul class="nav nav-tabs">
                                    <li class="nav-item">
                                        <a class="nav-link active" data-toggle="tab" href="#hs">Penjanringan Kesehatan</a>
                                    </li>
                                    <li class="nav-item">
                                    <a class="nav-link" data-toggle="tab" href="#mh">Kesehatan Mental</a>
                                    </li>
                                    {{-- <li class="nav-item">
                                      <a class="nav-link" data-toggle="tab" href="#mhh">Kesehatan Mental 2</a>
                                    </li> --}}
                                    <li class="nav-item">
                                      <a class="nav-link" data-toggle="tab" href="#lm">Modalitas Belajar</a>
                                    </li>
                                    <li class="nav-item">
                                      <a class="nav-link" data-toggle="tab" href="#bd">Dominasi Otak</a>
                                    </li>
                                </ul>
                                  <!-- Tab panes -->
                                  <div class="tab-content">
                                    <div class="tab-pane container active" id="hs">
                                        @isset($record)
                                        @include('admin.medical_record.health_screening',['record'=>$record])
                                        @else
                                        @include('admin.medical_record.health_screening')
                                        @endisset
                                    </div>
                                    <div class="tab-pane container fade" id="mh">
                                        @include('admin.medical_record.mental_health')
                                    </div>
                                    {{-- <div class="tab-pane container fade" id="mhh">
                                        @include('admin.medical_record.mental_health2')
                                    </div> --}}
                                    <div class="tab-pane container fade" id="lm">
                                        @include('admin.medical_record.learning_modality')
                                    </div>
                                    <div class="tab-pane container fade" id="bd">
                                        @include('admin.medical_record.brain_domination')
                                    </div>
                                  </div>
                                  <input type="hidden" name="student_nis" value="{{$student->nis}}">
                                <div class="form-group">
                                    <input type="submit" value="Simpan" class="btn btn-primary">
                                    <a href="{{URL::previous()}}" class="btn btn-danger">Batal</a>
                                </div>
                            </form>
                        </div>
                </div>
            </div>
            @endisset
        </div>
    </div>
</section>
@endsection

@section('custom-script')
<script type="text/javascript">
$(function () {
    $('.mental-health').keyup(function () {
        var hasilE=parseInt($('#mh3').val())+parseInt($('#mh8').val())+parseInt($('#mh13').val())+parseInt($('#mh16').val())+parseInt($('#mh24').val());
        var hasilC=parseInt($('#mh5').val())+parseInt($('#mh7').val())+parseInt($('#mh12').val())+parseInt($('#mh18').val())+parseInt($('#mh22').val());
        var hasilH=parseInt($('#mh2').val())+parseInt($('#mh10').val())+parseInt($('#mh15').val())+parseInt($('#mh21').val())+parseInt($('#mh25').val());
        var hasilP=parseInt($('#mh6').val())+parseInt($('#mh11').val())+parseInt($('#mh14').val())+parseInt($('#mh19').val())+parseInt($('#mh23').val());
        var hasilPr=parseInt($('#mh1').val())+parseInt($('#mh4').val())+parseInt($('#mh9').val())+parseInt($('#mh17').val())+parseInt($('#mh20').val());
        $('#e').html(hasilE);
        $('#c').html(hasilC);
        $('#h').html(hasilH);
        $('#p').html(hasilP);
        $('#pr').html(hasilPr);

        var hasilDifficulty = hasilE+hasilC+hasilH+hasilP;
        var hasilStrength = hasilPr;

        $('#difficulty').html(hasilDifficulty);
        $('#strength').html(hasilStrength);
    });

    $('.learning-modality').keyup(function () {
        var hasilV=parseInt($('#lm1').val())+parseInt($('#lm2').val())+parseInt($('#lm4').val())+parseInt($('#lm5').val())+parseInt($('#lm8').val())+parseInt($('#lm9').val())+parseInt($('#lm11').val())+parseInt($('#lm23').val());
        var hasilA=parseInt($('#lm2').val())+parseInt($('#lm6').val())+parseInt($('#lm112').val())+parseInt($('#lm13').val())+parseInt($('#lm14').val())+parseInt($('#lm15').val())+parseInt($('#lm16').val())+parseInt($('#lm17').val());
        var hasilK=parseInt($('#lm7').val())+parseInt($('#lm10').val())+parseInt($('#lm18').val())+parseInt($('#lm19').val())+parseInt($('#lm20').val())+parseInt($('#lm21').val())+parseInt($('#lm22').val())+parseInt($('#lm24').val());

        $('#v').html(hasilV);
        $('#a').html(hasilA);
        $('#k').html(hasilK);

        var scoreV = "belum optimal";
        var scoreA = "belum optimal";
        var scoreK = "belum optimal";

        if (hasilV>=18) {
            scoreV="optimal";
        }else if (hasilV>=12) {
            scoreV="cukup optimal";
        }

        if (hasilA>=18) {
            scoreA="optimal";
        }else if (hasilA>=12) {
            scoreA="cukup optimal";
        }

        if (hasilK>=18) {
            scoreK="optimal";
        }else if (hasilK>=12) {
            scoreK="cukup optimal";
        }

        $('#scorev').html(scoreV);
        $('#scorea').html(scoreA);
        $('#scorek').html(scoreK);

    });

    $('.brain-domination').keyup(function () {
        var total=parseInt($('#bd1').val())+
        parseInt($('#bd3').val())+
        parseInt($('#bd4').val())+
        parseInt($('#bd5').val())+
        parseInt($('#bd6').val())+
        parseInt($('#bd7').val())+
        parseInt($('#bd8').val())+
        parseInt($('#bd9').val())+
        parseInt($('#bd10').val())+
        parseInt($('#bd11').val())+
        parseInt($('#bd12').val())+
        parseInt($('#bd13').val())+
        parseInt($('#bd14').val())+
        parseInt($('#bd15').val())+
        parseInt($('#bd16').val())+
        parseInt($('#bd17').val())+
        parseInt($('#bd18').val())+
        parseInt($('#bd19').val())+
        parseInt($('#bd20').val());

        var result = "";

        if (total<=4) {
            result="sangat otak kiri";
        }else if (total<=8) {
            result="lebih otak kiri";
        }else if (total<=12) {
            result="otak kiri-kanan";
        }else if (total<=16) {
            result="lebih otak kanan";
        }else if (total<=20) {
            result="sangat otak kanan";
        }
        $('#interpretation').html(result);
    });

})
$(window).on('load', function() {
 console.log("sadas");
});

</script>
@endsection

resources/views/admin/medical_record/index3.blade.php
@extends('layouts.layout')

@section('content')
<!-- Breadcrumb-->
<div class="breadcrumb-holder">
    <div class="container-fluid">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="index.html">Home</a></li>
            <li class="breadcrumb-item active">Rekam Medik </li>
        </ul>
    </div>
</div>
<section>
    <div class="container-fluid">
        <!-- Page Header-->
        <header>
            <h1 class="h3 display">List Data Rekam Medik </h1>
        </header>
        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        @endif
        @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
        @endif
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header">
                        <h4 style="float:left">
                            {{$student->name}}
                        </h4>
                        <div style="float:right">
                            <a href="{{route('rekam-medik2.create',$student->nis)}}" class="btn btn-primary btn-sm">Tambah</a>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Tanggal Pelaksanaan</th>
                                        <th>Aksi</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php $x=1;?>
                                    @foreach ($records as $item)
                                    <tr>
                                        <th scope="row">{{$x++}}</th>
                                        <td>{{date('d-m-Y',strtotime($item->date))}}</td>
                                        <td>
                                            <form action="{{ route('rekam-medik.destroy',$item->id) }}" method="POST">
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit" onclick="return confirm('Apakah anda yakin?')"
                                                    class="btn btn-danger btn-sm"><i
                                                        class="fa fa-trash"></i></button>

                                                <a href="{{route('rekam-medik.edit',$item->id)}}"
                                                    class="btn btn-warning btn-sm"><i class="fa fa-edit"></i></a>
                                                <a href="{{route('rekam-medik.show',$item->id)}}"
                                                    class="btn btn-primary btn-sm"><i class="fa fa-eye"></i></a>
                                            </form>
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection