routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('admin.health.tau');
// });
Route::get('/tes','DashboardController@tes');

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');
Route::group(['middleware' => ['admin'], 'prefix' => 'admin/surat'], function () {
    Route::get('surat-rujukan-kesehatan-anak-sekolah', 'letterController@indexSRKAS')->name('letter.index.srkas');
    Route::post('surat-rujukan-kesehatan-anak-sekolah', 'letterController@printSRKAS')->name('letter.print.srkas');
    Route::get('surat-rujukan-balik', 'letterController@indexRujukBlk')->name('letter.index.rujukblk');
    Route::post('surat-rujukan-balik', 'letterController@printRujukBlk')->name('letter.print.rujukblk');
    Route::get('surat-rujukan-UKS', 'letterController@indexRujukUKS')->name('letter.index.rujukuks');
    Route::post('surat-rujukan-UKS', 'letterController@printRujukUKS')->name('letter.print.rujukuks');
    Route::get('kartu-kontrol','DashboardController@indexkk')->name('karkon.index');
    Route::post('kartu-kontrol','DashboardController@cetak')->name('karkon.cetak');
});

Route::group(['middleware'=>'admin', 'prefix' => 'admin'], function () {
    Route::get('/','DashboardController@index')->name('admin.home');
    Route::resource('user', 'UserController');
    Route::resource('siswa', 'StudentController');
    Route::resource('kesehatan', 'HealthController');
    Route::resource('imunisasi', 'ImmunizationHistoryController');
    Route::resource('status-gizi', 'MeasurementController');
    Route::resource('rekam-medik', 'MedicalRecordController');
    Route::resource('kelas', 'ClassroomController');

    Route::get('siswa-export','StudentController@export')->name('siswa.export');
    Route::post('siswa-import','StudentController@import')->name('siswa.import');

    Route::get('kesehatan/student/{id}', 'HealthController@indexHealth')->name('student.find.health');
    Route::get('kesehatan/create/{id}', 'HealthController@create')->name('kesehatan2.create');

    Route::get('imunisasi/student/{id}', 'ImmunizationHistoryController@indexImmune')->name('student.find.immune');
    Route::get('imunisasi/create/{id}', 'ImmunizationHistoryController@create')->name('imunisasi2.create');

    Route::get('rekam-medik/student/{id}', 'MedicalRecordController@indexMedRec')->name('student.find.record');
    Route::get('rekam-medik/create/{id}', 'MedicalRecordController@create')->name('rekam-medik2.create');

    Route::post('users/update', 'HomeController@tested');
});


// for testing
if (app()->environment(['local', 'staging'])) {
    Route::get('tes',function (){
        return view('welcome');
    });
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Support\Facades\Hash;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'no_identity',
        'name',
        'email',
        'phone_number',
        'position',
        'user_type',
        'password',
        'avatar',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function setPasswordAttribute($value)
    {
        if($value != ""){
            $this->attributes['password'] = Hash::make($value);
        }
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\CategoryUser;
use App\User;
use Illuminate\Http\Request;
use App\Http\Requests\StroreUserRequest;
use App\Http\Requests\UpdateUserRequest;
use Intervention\Image\Facades\Image;
use DataTables;
use Illuminate\Support\Facades\File;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();
        return view('admin.user.index',compact('users'));
    }

    public function index2(Request $request)
    {
        if ($request->ajax()) {
            $data = User::latest()->get();
            return Datatables::of($data)
                    ->addIndexColumn()
                    ->addColumn('action', function($data){
                           return '<a href="#" class="xedit"
                           data-pk='.$data->id.'
                           data-name="phone_number">
                           '.$data->phone_number.'</a>';
                    })
                    ->rawColumns(['action'])
                    ->make(true);
        }
        $users = User::all();
        return view('admin.user.index',compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $userTypes = ['staff','admin'];
        return view('admin.user.form',compact('userTypes'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StroreUserRequest $request)
    {
        if ($request->hasFile('avatar') && $request->has('avatar')) {
            $avatar = $request->file('avatar');
            $filename = time() . '.' . $avatar->getClientOriginalExtension();

            Image::make($avatar)->resize(354,472)->save(public_path('/uploads/avatars/' . $filename));
            $user = User::create($request->all());
            $user->avatar = $filename;
            $user->save();
            return redirect()->route('user.index')->with('success','Berhasil menambah data');
        }
        User::create($request->all());
        return redirect()->route('user.index')->with('success','Berhasil menambah data');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\user  $user
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::find($id);
        return view('admin.user.show',compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\user  $user
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::findOrFail($id);
        $userTypes = ['staff','admin'];
        return view('admin.user.form',compact('user','userTypes'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\user  $user
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateUserRequest $request,$id)
    {
        $user = User::findOrFail($id);
        if ($request->hasFile('avatar')) {
            # code...
            $pathToFile = public_path('uploads/avatars/' . $user->avatar);
            File::delete($pathToFile);
            $avatar = $request->file('avatar');
            $filename = time() . '.' . $avatar->getClientOriginalExtension();
            Image::make($avatar)->resize(354,472)->save(public_path('/uploads/avatars/' . $filename));
            $user->avatar =  $filename;
        }
        $user->update($request->all());
        return redirect()->route('user.index')->with('success','Berhasil merubah data');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\user  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (auth()->user()->id==$id) {
            # code...
            return back()->withErrors(['Tidak Bisa Menghapus Akun yang sedang digunakan']);
        }
        $user=User::find($id);
        $pathToFile = public_path('uploads/avatars/' . $user->avatar);
        File::delete($pathToFile);
        $user->delete();
        return redirect()->route('user.index')->with('success','Berhasil menghapus data');
    }


}

resources/views/admin/user/edit.blade.php
@extends('admin.layout')
@section('content')
<section class="forms">
    <div class="container-fluid">
        <!-- Page Header-->
        <header>
            <h1 class="h3 display">Pengguna </h1>
        </header>
        <div class="row">
            @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
            @endif
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header d-flex align-items-center">
                        <h4>Tambah Pengguna</h4>
                    </div>
                    <div class="card-body">
                        <p>Silahkan Tambahkan data Pengguna</p>
                        <form enctype="multipart/form-data" action="{{route('user.update',$user->id)}}" method="POST">
                            @csrf
                            @method('PUT')
                            <div class="form-group">
                                <label>Nama Lengkap</label>
                                <input type="text" name="name" placeholder="Masukan Nama Lengkap" class="form-control"
                                    value="{{$user->name}}" required>
                            </div>
                            <div class="form-group">
                                <label>Nomor HP</label>
                                <input type="text" name="phone_number" placeholder="Masukan Nomor HP" class="form-control"
                                    value="{{$user->phone_number}}" required>
                            </div>
                            <div class="form-group">
                                <label>Email</label>
                                <input type="email" placeholder="Masukan Email" name="email" class="form-control"
                                    value="{{$user->email}}" required>
                            </div>
                            <div class="form-group">
                                <label>Password Saat Ini</label>
                                <input type="password" placeholder="Tidak perlu diisi jika tidak ingin merubah"
                                    name="current_password" class="form-control" autocomplete="current_password">
                            </div>
                            <div class="form-group">
                                <label>Password Baru</label>
                                <input type="password" placeholder="Tidak perlu diisi jika tidak ingin merubah"
                                    name="password" class="form-control" autocomplete="password">
                            </div>
                            <div class="form-group">
                                <label>Konfirmasi Password Baru</label>
                                <input type="password" placeholder="Tidak perlu diisi jika tidak ingin merubah"
                                    name="new_confirm_password" class="form-control" autocomplete="new_confirm_password">
                            </div>

                            <div class="form-group">
                                <label>Status</label>
                                <select name="category_user_id" class="custom-select">
                                    @foreach ($categories as $item)
                                    <option value={{$item->id}}
                                        @if ($item->id == $user->category_user_id) selected @endif>{{$item->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Foto saat ini</label>
                                <img src="{{asset('/uploads/avatars/'.$user->avatar)}}" alt="belum pernah upload foto"
                                    style="width:155px; height:255px; display:block; border-radius:10%;">
                            </div>
                            <div class="form-group">
                                <label>Upload Foto Baru</label>
                                <input type="file" class="form-control-file" name="avatar">
                            </div>
                            <br>
                            <div class="form-group">
                                <input type="submit" value="Simpan" class="btn btn-primary">
                                <a href="{{URL::previous()}}" class="btn btn-danger">Batal</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

        </div>
    </div>
</section>
@endsection

resources/views/admin/user/form.blade.php
@extends('layouts.layout')

@section('content')
<!-- Breadcrumb-->
<div class="breadcrumb-holder">
    <div class="container-fluid">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="index.html">Home</a></li>
            <li class="breadcrumb-item active">Pengguna </li>
        </ul>
    </div>
</div>
<section>
    <div class="container-fluid">
        <!-- Page Header-->
        <header>
            <h1 class="h3 display">Pengguna </h1>
        </header>
        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                <li>Proses Gagal!!!</li>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        @endif
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                        @isset ($user)
                        <div class="card-header d-flex align-items-center">
                            <h4>Ubah Pengguna</h4>
                        </div>
                        <div class="card-body">
                        <form enctype="multipart/form-data" action="{{route('user.update',$user->id)}}" method="POST">
                            @method('PUT')
                            @else
                            <div class="card-header d-flex align-items-center">
                                <h4>Tambah Pengguna</h4>
                            </div>
                            <div class="card-body">
                            <form enctype="multipart/form-data" action="{{route('user.store')}}" method="POST">
                                @endisset
                                @csrf
                                <div class="form-group">
                                    <label>No Identitas</label>
                                    <input type="text" name="no_identity" placeholder="Masukan Nomor Identitas"
                                        class="form-control" value="{{old('no_identity',$user->no_identity ?? ' ')}}" required>
                                </div>
                                <div class="form-group">
                                    <label>Nama Lengkap</label>
                                    <input type="text" name="name" placeholder="Masukan Nama Lengkap"
                                        class="form-control" value="{{old('name',$user->name ?? ' ')}}" required>
                                </div>
                                <div class="form-group">
                                    <label>Nomor HP</label>
                                    <input type="text" name="phone_number" placeholder="Masukan Nomor HP"
                                        class="form-control" value="{{old('phone_number',$user->phone_number ?? ' ')}}"
                                        required>
                                </div>
                                <div class="form-group">
                                    <label>Email</label>
                                    <input type="email" name="email" class="form-control"
                                        value="{{old('email',$user->email ?? ' ')}}" required>
                                </div>
                                <div class="form-group">
                                    <label>Jabatan</label>
                                    <input type="text" name="position" placeholder="Masukan Jabatan"
                                        class="form-control" value="{{old('position',$user->position ?? ' ')}}" required>
                                </div>
                                @isset ($user)
                                <div class="form-group">
                                    <label>Password Saat Ini</label>
                                    <input type="password" placeholder="Tidak perlu diisi jika tidak ingin merubah"
                                        name="current_password" class="form-control" autocomplete="current_password">
                                </div>
                                <div class="form-group">
                                    <label>Password Baru</label>
                                    <input type="password" placeholder="Tidak perlu diisi jika tidak ingin merubah"
                                        name="password" class="form-control" autocomplete="password">
                                </div>
                                <div class="form-group">
                                    <label>Konfirmasi Password Baru</label>
                                    <input type="password" placeholder="Tidak perlu diisi jika tidak ingin merubah"
                                        name="new_confirm_password" class="form-control"
                                        autocomplete="new_confirm_password">
                                </div>
                                @else
                                <div class="form-group">
                                    <label>Password</label>
                                    <input type="password" name="password" class="form-control" required>
                                </div>
                                @endisset

                                <div class="form-group">
                                    <label>Jenis Akun</label>
                                    <select name="user_type" class="custom-select">
                                        @isset ($user)
                                        @foreach ($userTypes as $item)
                                        <option value={{$item}} @if ($item == $user->user_type) selected
                                            @endif>{{$item}}</option>
                                        @endforeach
                                        @else
                                        <option value='' selected disabled>--Pilih--</option>
                                        @foreach ($userTypes as $item)
                                        <option value={{$item}}>{{$item}}</option>
                                        @endforeach
                                        @endisset
                                    </select>
                                </div>
                                <div class="form-group">
                                    @isset ($user)
                                    <div class="form-group">
                                        <label>Foto saat ini</label>
                                        <img src="{{asset('/uploads/avatars/'.$user->avatar)}}"
                                            alt="belum pernah upload foto"
                                            style="width:155px; height:255px; display:block; border-radius:10%;">
                                    </div>
                                    <div class="form-group">
                                        <label>Upload Foto Baru</label>
                                        <input type="file" class="form-control-file" name="avatar">
                                    </div>
                                    @else
                                    <label>Foto</label>
                                    <input type="file" class="form-control-file" name="avatar">
                                    @endisset

                                </div>
                                <br>
                                <div class="form-group">
                                    <input type="submit" value="Simpan" class="btn btn-primary">
                                    <a href="{{URL::previous()}}" class="btn btn-danger">Batal</a>
                                </div>
                            </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

resources/views/admin/user/index.blade.php
@extends('layouts.layout')

@section('content')
<!-- Breadcrumb-->
<div class="breadcrumb-holder">
    <div class="container-fluid">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="index.html">Home</a></li>
            <li class="breadcrumb-item active">Pengguna </li>
        </ul>
    </div>
</div>
<section>
    <div class="container-fluid">
        <!-- Page Header-->
        <header>
            <h1 class="h3 display">Pengguna </h1>
        </header>
        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        @endif
        @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
        @endif
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header">
                        <h4 style="float:left"></h4>
                        <div style="float:right">
                            <a href="{{route('user.create')}}" class="btn btn-primary btn-sm">Tambah</a>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Nama</th>
                                        <th>Email</th>
                                        <th>No Hp</th>
                                        <th>Aksi</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php $x=1;?>
                                    @foreach ($users as $item)
                                    <tr>
                                        <th scope="row">{{$x++}}</th>
                                        <td>{{$item->name}}</td>
                                        <td>{{$item->email}}</td>
                                        <td>{{$item->phone_number}}</td>
                                        <td>
                                            <form action="{{ route('user.destroy',$item->id) }}" method="POST">
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit" onclick="return confirm('Apakah anda yakin?')"
                                                    class="btn btn-danger btn-sm"><i
                                                        class="fa fa-trash"></i></button>

                                                <a href="{{route('user.edit',$item->id)}}"
                                                    class="btn btn-warning btn-sm"><i class="fa fa-edit"></i></a>
                                                <a href="{{route('user.show',$item->id)}}"
                                                    class="btn btn-primary btn-sm"><i class="fa fa-eye"></i></a>
                                            </form>
                                        </td>
                                    </tr>

                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

resources/views/admin/user/show.blade.php
@extends('admin.layout')
@section('content')
<section class="forms">
        <div class="container-fluid">
          <!-- Page Header-->
          <header>
            <h1 class="h3 display">Pengguna            </h1>
      </header>
          <div class="row">
            @if ($message = Session::get('success'))
                <div class="alert alert-success">
                    <p>{{ $message }}</p>
            </div>
            @endif
            <div class="col-lg-12">
                    <div class="card bg-light">
                            <div class="card-header">Profil Pengguna</div>
                                <div class="card-body">
                                    <div class="row" >
                                        <div class="col-lg-2">
                                                <img class="card-img-top" src="{{asset('/uploads/avatars/'.$user->avatar)}}" alt="Card image">
                                    </div>

                                        <div class="col-lg-7">
                                            <table class="table table-striped" style="width:100%">
                                                <tbody>
                                                <tr>
                                                    <th>
                                                        Nama<br>
                                                        Email<br>
                                                        Nomor HP

                                                </th>
                                                    <td></td>
                                                    <td>
                                                        {{$user->name}}<br>
                                                        {{$user->email}}<br>
                                                        {{$user->no_hp}}<br>
                                                </td>
                                            </tr>
                                            </tbody>
                                        </table>
                                            <a href="{{route('user.index')}}" class="btn btn-primary">Kembali</a>
                                    </div>
                                </div>
                            </div>
                    </div>

        </div>
      </div>
    </div>
  </section>
@endsection